### ISSUE TITLE
Both problem and negation unsat

### ISSUE THREAD

**Issue by zenna** [dreal/dreal3#129] opened 2015-06-04 23:33 UTC
```
(set-logic QF_NRA)
(declare-fun omega0 () Real)
(declare-fun omega1 () Real)
(assert (>= omega0 0.5312500000000001))
(assert (<= omega0 0.5625))
(assert (>= omega1 0.5000000000000001))
(assert (<= omega1 0.53125))
(assert (and (<= (abs (- (+ (* (+ (* 4 omega0) -2) (+ (* 4 omega0) -2)) (* (+ (* 4 omega1) -2) (+ (* 4 omega1) -2))) 0.1)) 0.0001) (> (asin (/ (+ (* 4 omega0) -2) (+ (* 4 omega1) -2))) 0.15915494309190006)))
(check-sat)
(exit)

(set-logic QF_NRA)
(declare-fun omega0 () Real)
(declare-fun omega1 () Real)
(assert (>= omega0 0.5312500000000001))
(assert (<= omega0 0.5625))
(assert (>= omega1 0.5000000000000001))
(assert (<= omega1 0.53125))
(assert (not (and (<= (abs (- (+ (* (+ (* 4 omega0) -2) (+ (* 4 omega0) -2)) (* (+ (* 4 omega1) -2) (+ (* 4 omega1) -2))) 0.1)) 0.0001) (> (asin (/ (+ (* 4 omega0) -2) (+ (* 4 omega1) -2))) 0.15915494309190006))))
(check-sat)
(exit)
```

**Comment by soonhokong** [comment] 2015-06-05 00:20
I think this is an upstream issue (in IBEX). I have a smaller example which is UNSAT and its negation is also UNSAT as well.

```
(set-logic QF_NRA)
(declare-fun omega0 () Real)
(declare-fun omega1 () Real)
(assert (>= omega0 0.5312500000000001))
(assert (<= omega0 0.5625))
(assert (>= omega1 0.5000000000000001))
(assert (<= omega1 0.53125))
(assert
 (> (asin (/ (+ (* 4 omega0) -2) (+ (* 4 omega1) -2))) 0.15915494309190006))
(check-sat)
(exit)
```

**Comment by soonhokong** [comment] 2015-06-05 00:21
I'll try to write a self-contained C++ code and report it to the IBEX team. Thanks for the report!

**Comment by soonhokong** [comment] 2015-06-05 00:25
hmm... it seems that the argument of `asin` is always out of its domain and that's why it's always UNSAT. I'll double check.

**Comment by soonhokong** [comment] 2015-06-05 15:54
@zenna and @scungao, this is what's happening here.

1. Let's say that we have a formula `∃x ∈ I. f(x) ∨ g(x)`. Note that `g(x)` is not defined in `I`. But we do have `∃x ∈ I. f(x)` is true so `∃x ∈ I. f(x) ∨ g(x)` is true as well.

2. When dReal handles a disjunction, it checks the following assignments in sequence since it seeks a complete assignment unless `--short-sat` option is being used:
   - `∃x ∈ I. f(x) ∧ g(x)`
   - `∃x ∈ I. f(x) ∧ ¬g(x)` 

3. Because both of `g(x)` and `¬g(x)` are false, the above two checks return UNSAT. dReal returns UNSAT as a result.

One workaround is to turn on `--short-sat` option. I checked that this gives the right answer (delta-SAT). @scungao, do you see any problem in my explanation? I think we need to fix this without relying on `--short-sat`.

**Comment by soonhokong** [comment] 2015-10-21 20:37
I'm checking this issue again, and I think this is not a bug. Consider the two examples:

Example1
```
(set-logic QF_NRA)
(declare-fun omega0 () Real)
(declare-fun omega1 () Real)
(assert (>= omega0 0.5312500000000001))
(assert (<= omega0 0.5625))
(assert (>= omega1 0.5000000000000001))
(assert (<= omega1 0.53125))
(assert
 (> (asin (+ omega0 omega1)) 0.15915494309190006))
(check-sat)
(exit)
```

Example2
```
(set-logic QF_NRA)
(declare-fun omega0 () Real)
(declare-fun omega1 () Real)
(assert (>= omega0 0.5312500000000001))
(assert (<= omega0 0.5625))
(assert (>= omega1 0.5000000000000001))
(assert (<= omega1 0.53125))
(assert
 (not (> (asin (+ omega0 omega1)) 0.15915494309190006)))
(check-sat)
(exit)
```

As you see, example2 is checking the negation of example 1. Naturally you expect one of them returning SAT.

However, dReal returns UNSAT for both of them. This is because of the argument of `omega0 + omega1` whose lower bound is `1.031`. Note that `asin` is only defined in [-1, 1]. As a result, it's not possible to satisfy either of examples. 

@zenna's original example is passing `(4 * omega0 - 2) / (4 * omega1 - 2)` to `asin` function where its lower bound is `(4 * 5.312500000000001 - 2) / (4 * 5.3125 - 2)` = `1.0000001` which is out of `asin`'s domain.

I'm closing this issue for now. Please feel free to add comments and let me know if you want to re-open it.

**Closed by soonhokong** 2015-10-21 20:37 UTC
Labels: bug
