### ISSUE TITLE
dReal v3.16.06 gives only upper bound when finding a model of "x > 0"

### ISSUE THREAD

**Issue by narechiga** [dreal/dreal3#259] opened 2016-06-16 23:45 UTC
Correct output is [0, +INFTY], but dReal returns [ +INFTY]. Added the smt2 and smt2.model files in a zip, because apparently github doesn't like smt2/smt2.model files.

[badquery.zip](https://github.com/dreal/dreal3/files/319548/badquery.zip)

**Comment by soonhokong** [comment] 2016-06-17 02:36
Further discussion revealed that it's due to the way we print out intervals with infinity. See [the code in the filib++](https://github.com/dreal-deps/filibxx/blob/master/interval/interval.icc#L1109-L1112) that we're depending on.

We agree to change the code so that we have `[+INFTY, +INFTY]` for `+oo` and `[-INFTY, -INFTY]` for `-oo`.

**Comment by soonhokong** [comment] 2016-06-17 02:45
Now it outputs:
```
Solution:
x : [ ENTIRE ] = [+INFTY, +INFTY]
delta-sat with delta = 0.00100000000000000
```

**Comment by soonhokong** [comment] 2016-06-17 02:47
You need to do `make update_pkgs`. I also picked up new commits for the new version of IBEX. I'll run regression tests and release a new version.

**Comment by narechiga** [comment] 2016-06-17 03:10
main concern is with the model file--what will the model file show?

**Comment by soonhokong** [comment] 2016-06-17 03:16
@narechiga, it's the same `[+INFTY, +INFTY]`:

```
delta-sat with the following box:
	x : [+INFTY, +INFTY]
```

**Comment by soonhokong** [comment] 2016-06-17 05:41
Closed by https://github.com/dreal-deps/filibxx/commit/614c01ba587ddff84b9fc144064cbf453398a668.

**Closed by soonhokong** 2016-06-17 05:41 UTC
Labels: enhancement
